# Generated by Django 5.2.7 on 2025-11-08 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Food & Groceries', 'Food & Groceries'), ('Transportation', 'Transportation'), ('Rent & Utilities', 'Rent & Utilities'), ('Health & Fitness', 'Health & Fitness'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Education', 'Education'), ('Travel', 'Travel'), ('Savings & Investments', 'Savings & Investments'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
